### ISSUE TITLE
proxy_url definition needs quotes to recognize  'None' as a value 

### ISSUE THREAD

**Issue by mcbrown87** [christian-schlichtherle/kalaxy#1] opened 2020-05-14 10:40 UTC
When trying to execute the playbook, it was applying the proxy url even though it was set to 'None'. I fixed it by adding quotes around all of the 'None' values.

**Comment by christian-schlichtherle** [comment] 2020-06-09 19:36
Do you mind sending a pull request?

**Comment by mcbrown87** [comment] 2020-06-09 19:46
I have the change in a local branch and it looks like I don't have permission to push to a remote branch

**Comment by christian-schlichtherle** [comment] 2020-06-10 08:06
You need to clone the project, push your changes to your clone and then open a pull request.

**Comment by christian-schlichtherle** [comment] 2020-08-19 19:07
I think this is caused by YAML parsing `None` as a string. I've replaced these defaults with `null` so that Python can translate it to `None`. This fix is included in version 0.6.7. Let me know if it works for you.

**Closed as completed** 2020-10-09 23:15 UTC
